<?php

namespace ContainerJUX7eJu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MQr4omAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MQr4omA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MQr4omA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'product' => ['privates', '.errored..service_locator.MQr4omA.App\\Entity\\Product', NULL, 'Cannot autowire service ".service_locator.MQr4omA": it references class "App\\Entity\\Product" but no such service exists.'],
            'stockRepository' => ['privates', 'App\\Repository\\StockRepository', 'getStockRepositoryService', true],
        ], [
            'manager' => '?',
            'product' => 'App\\Entity\\Product',
            'stockRepository' => 'App\\Repository\\StockRepository',
        ]);
    }
}
