<?php

namespace ContainerJUX7eJu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WXOkwneService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WXOkwne' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WXOkwne'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'size' => ['privates', '.errored..service_locator.WXOkwne.App\\Entity\\Size', NULL, 'Cannot autowire service ".service_locator.WXOkwne": it references class "App\\Entity\\Size" but no such service exists.'],
        ], [
            'manager' => '?',
            'size' => 'App\\Entity\\Size',
        ]);
    }
}
