<?php

namespace ContainerJUX7eJu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WsGndWuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WsGndWu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WsGndWu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'color' => ['privates', '.errored..service_locator.WsGndWu.App\\Entity\\Color', NULL, 'Cannot autowire service ".service_locator.WsGndWu": it references class "App\\Entity\\Color" but no such service exists.'],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'color' => 'App\\Entity\\Color',
            'manager' => '?',
        ]);
    }
}
