<?php

namespace ContainerJUX7eJu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSizeTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\SizeType' shared autowired service.
     *
     * @return \App\Form\SizeType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/SizeType.php';

        return $container->privates['App\\Form\\SizeType'] = new \App\Form\SizeType();
    }
}
