<?php

namespace ContainerJUX7eJu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuppliersService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.RBwYpTW.App\Entity\Suppliers' shared service.
     *
     * @return \App\Entity\Suppliers
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.RBwYpTW": it references class "App\\Entity\\Suppliers" but no such service exists.');
    }
}
