<?php

namespace ContainerQx5juKx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RBwYpTWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RBwYpTW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RBwYpTW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'repository' => ['privates', 'App\\Repository\\SuppliersRepository', 'getSuppliersRepositoryService', true],
            'suppliers' => ['privates', '.errored..service_locator.RBwYpTW.App\\Entity\\Suppliers', NULL, 'Cannot autowire service ".service_locator.RBwYpTW": it references class "App\\Entity\\Suppliers" but no such service exists.'],
        ], [
            'manager' => '?',
            'repository' => 'App\\Repository\\SuppliersRepository',
            'suppliers' => 'App\\Entity\\Suppliers',
        ]);
    }
}
