<?php

namespace ContainerQx5juKx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RhFpmrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RhFpmr_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RhFpmr_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'subCategory' => ['privates', '.errored..service_locator.RhFpmr_.App\\Entity\\SubCategory', NULL, 'Cannot autowire service ".service_locator.RhFpmr_": it references class "App\\Entity\\SubCategory" but no such service exists.'],
        ], [
            'manager' => '?',
            'subCategory' => 'App\\Entity\\SubCategory',
        ]);
    }
}
