<?php

namespace ContainerQx5juKx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SeUXItpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.seUXItp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.seUXItp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'deliveryRepository' => ['privates', 'App\\Repository\\DeliveryRepository', 'getDeliveryRepositoryService', true],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'orderRepository' => ['privates', 'App\\Repository\\OrderRepository', 'getOrderRepositoryService', true],
        ], [
            'deliveryRepository' => 'App\\Repository\\DeliveryRepository',
            'manager' => '?',
            'orderRepository' => 'App\\Repository\\OrderRepository',
        ]);
    }
}
