<?php

namespace ContainerQx5juKx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPanierServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Panier\PanierService' shared autowired service.
     *
     * @return \App\Service\Panier\PanierService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/Panier/PanierService.php';

        return $container->privates['App\\Service\\Panier\\PanierService'] = new \App\Service\Panier\PanierService(($container->services['.container.private.session'] ?? $container->load('get_Container_Private_SessionService')), ($container->privates['App\\Repository\\ProductRepository'] ?? $container->load('getProductRepositoryService')), ($container->privates['App\\Repository\\ColorRepository'] ?? $container->load('getColorRepositoryService')), ($container->privates['App\\Repository\\SizeRepository'] ?? $container->load('getSizeRepositoryService')));
    }
}
