<?php

namespace ContainerQx5juKx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSizeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.WXOkwne.App\Entity\Size' shared service.
     *
     * @return \App\Entity\Size
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.WXOkwne": it references class "App\\Entity\\Size" but no such service exists.');
    }
}
